### ISSUE TITLE
Fixing Redirection

### ISSUE THREAD

**Issue by baishali-ghosh** [TheProphet007/IEEE-CS-Core-Committee-Selection#2]
Hello guys, let's leverage Github issues to discuss about roadblocks and any issues you might face while implementing specific functionalities. Now if someone can brief me in on what exactly is required here, it would be quite useful.

**Comment by TheProphet007** [comment]
Um, didi, basically we are creating an exam thats gonna be hosted on a local server. The QP directory contains the models for the Question and Answer and the questions with their respective answers will be added later in the admin page(we have already created two sample questions). The homepage has been modified to a login page which will then redirect the student to the first exam containing the questions that are have been created through the admin login (that part has been fixed as in if we separately open up the port/junior page, we can see the questions).  Home directory is for the modifications to the home page i.e, where the login is done. 
Now, the problem we are facing is the routing part. On clicking login, we want the page to redirect to the server/juniors page. But on clicking the login button, nothing seems to be happening. So we reached this level and we need help in routing to that particular page which displays the questions to the person writing the test.

**Comment by baishali-ghosh** [comment]
I've fixed that issue in another branch called Alternate. Take a look at the index.html under home and I've also changed the url handling and views to a bare minimum for testing purposes. So, I removed some code to get the redirection to work. You guys can go through that in the meanwhile and make changes accordingly in master.

**Comment by TheProphet007** [comment]
Okay will see
